cluster:
  mkdir -p logs &&
  sbatch
    --cpus-per-task={threads}
    --cores={threads}
    --mem={resources.mem_mb}
    --time="24:00:00"
    --job-name={rule}
    --output=logs/{rule}.out
    --error=logs/{rule}.err
    --parsable 

default-resources:
  - time="24:00:00" 
  - mem_mb=2000
slurm: True 
